# fly.toml app configuration file for FastAPI + Postgres

app = 'hng-backend-stage1'
primary_region = 'jnb'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
